name: git-kura CI

on:
  pull_request:
    paths:
      - "Formula/git-kura.rb"
      - ".github/workflows/ci-git-kura.yml"
      - ".github/workflows/reusable-formula-ci.yml"
  push:
    branches:
      - main
    paths:
      - "Formula/git-kura.rb"
      - ".github/workflows/ci-git-kura.yml"
      - ".github/workflows/reusable-formula-ci.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: homebrew-tap-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/reusable-formula-ci.yml
    permissions:
      contents: read
    with:
      formula: git-kura
